### ISSUE TITLE
Tuning Spaces from rbv2

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3tuningspaces#1]
Get them from [here](https://github.com/compstat-lmu/paper_2021_multi_fidelity_surrogates/blob/main/R/BenchmarkConfigs.R), perhaps use them with suffix `rbv2` or something? 
(You might have to scroll down a little to find them. the `trainsize` and `repl` params need to be removed.)

**Comment by be-marc** [comment]
Thanks. Done!
