### ISSUE TITLE
`browser()` statement in `lts.Learner()` intentional?

### ISSUE THREAD

**Issue by asiripanich** [mlr-org/mlr3tuningspaces#13]
Was this `browser()` statement intentionally put there? if yes, what is the use for it there? :)

https://github.com/mlr-org/mlr3tuningspaces/blob/6187058e634e62c8d81deea76dd789e51c1b0c7b/R/sugar.R#L31

**Comment by be-marc** [comment]
Thanks for reporting. Fixed by a5a0ca33cd7d022b1fdac4f35215276ddb3a48c5.
