### ISSUE TITLE
regr.xgboost.rbv2 and classif.xgboost.rbv2 - nrounds

### ISSUE THREAD

**Issue by markus-schaffer** [mlr-org/mlr3tuningspaces#35]
### Description

The setting of _nrounds_ for regr.xgboost.rbv2 and classif.xgboost.rbv2 deviate from Kuehn et al. (2018). It should be [1,5000] but is defined as `p_dbl(lower = 2, upper = 8, trafo = function(x) as.integer(round(exp(x))))`. 

### Reproducible example

``` 
    library(mlr3tuningspaces)
    tuning_space_xgboost <- lts("regr.xgboost.rbv2")
    tuning_space_xgboost$values$nrounds
```

**Comment by be-marc** [comment]
The source of the search space is wrong. It is Binder, Pfisterer, and Bischl (2020) - Collecting Empirical Data About Hyperparameters for Data Driven AutoML. Fixed in #36 which also adds the search space by Kuehn et al. (2018). Thank you.
