### ISSUE TITLE
bibentry for default tuningspaces can be updated to the paper 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3tuningspaces#40]
@article{bischl2023hyperparameter,
  title={Hyperparameter optimization: Foundations, algorithms, best practices, and open challenges},
  author={Bischl, Bernd and Binder, Martin and Lang, Michel and Pielok, Tobias and Richter, Jakob and Coors, Stefan and Thomas, Janek and Ullmann, Theresa and Becker, Marc and Boulesteix, Anne-Laure and others},
  journal={Wiley Interdisciplinary Reviews: Data Mining and Knowledge Discovery},
  volume={13},
  number={2},
  pages={e1484},
  year={2023},
  publisher={Wiley Online Library}
}

**Comment by be-marc** [comment]
Thanks. Done.
