### ISSUE TITLE
Tuning spaces have numeric parameters that should be integer

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3tuningspaces#42]
### Description

For example `classif.rpart.minsplit` and `classif.rpart.minbucket` are defined as numeric parameters in the default tuning space, but only integer values make sense.

### Reproducible example

See https://stackoverflow.com/questions/76826490/why-are-tuned-minsplit-minbucket-from-rpart-decimal-numbers

**Comment by be-marc** [comment]
The search space of `minsplit` and `minbucket` is defined on the logarithmic scale. Should be correct like this.
